is: [ auth ]
#securedBy: [ jwt: { roles: owner }]
type:
  collection:
    humanName: user
    schemaBaseName: user
    exampleGetResponse: !include ../examples/users/response-array-get.json
    examplePostRequest: !include ../examples/users/request-post.json
    examplePostError: !include ../examples/users/response-post-error.json

/{userId}:
  is: [ auth ]
  type:
    member:
      humanName: user
      schemaBaseName: user
      identifierName: userId
      exampleGetResponse: !include ../examples/users/response-get.json
      examplePatchRequest: !include ../examples/users/request-patch.json
      examplePatchError: !include ../examples/users/response-patch-error.json
  patch:
